#!/bin/sh -efu

if [ -z "${__include_vm_options-}" ]; then
__include_vm_options=1

. shell-git-config

get_qemu_monitor_default() {
	local vm_profiles=
	git_config_get vm_profiles "$vm_config_file" "vm.profiles"
	printf 'qmp:unix:%s/%s/socket,server,nowait' "$vm_profiles" "$vm_profile"
}

parameter \
	'qemu_machine' \
	'one' \
	'machine' \
	'machine' \
	'type=q35,accel=kvm:tcg' \
	'Specifying the emulated machine'

parameter \
	'qemu_arch' \
	'one' \
	'arch' \
	'arch' \
	'x86_64' \
	'Specifying target architecture'

parameter \
	'qemu_cpu' \
	'one' \
	'cpu-model' \
	'cpu-model' \
	'kvm64' \
	'Specifying CPU model'

parameter \
	'qemu_cpus' \
	'one' \
	'num-cpus' \
	'num-cpus' \
	'$(getconf _NPROCESSORS_ONLN)' \
	'Simulate an SMP system with n CPUs'

parameter \
	'qemu_memory' \
	'one' \
	'memory' \
	'memory' \
	'$(( 64 * ($qemu_cpus_default + 3) ))M' \
	'Specifying virtual RAM size'

parameter \
	'qemu_console' \
	'one' \
	'console' \
	'console' \
	'serial' \
	'Specifying console type'

parameter \
	'qemu_network' \
	'one' \
	'network' \
	'network' \
	'none' \
	'Specifying the mode network stack'

parameter \
	'qemu_kernel' \
	'one' \
	'kernel' \
	'kernel' \
	'' \
	'Use bzImage as kernel image'

parameter \
	'qemu_initrd' \
	'one' \
	'initrd' \
	'initrd' \
	'' \
	'Use file as initial ram disk'

parameter \
	'qemu_append' \
	'one' \
	'append' \
	'append' \
	'' \
	'Use cmdline as kernel command line'

parameter \
	'qemu_addappend' \
	'one' \
	'addappend' \
	'addappend' \
	'' \
	'The kernel parameters from the specified string'

parameter \
	'qemu_balloon' \
	'one_bool' \
	'balloon' \
	'balloon' \
	'false' \
	'Enable virtio balloon device'

parameter \
	'qemu_kvm' \
	'one_bool' \
	'enable-kvm' \
	'enable-kvm' \
	'false' \
	'Enable KVM full virtualization support'

parameter \
	'qemu_reboot' \
	'one_bool' \
	'reboot' \
	'reboot' \
	'false' \
	'Exit instead of rebooting'

parameter \
	'qemu_monitor' \
	'one' \
	'monitor' \
	'monitor' \
	'\$(get_qemu_monitor_default)' \
	'Redirect the monitor to host device'

parameter \
	'qemu_graphic' \
	'one_bool' \
	'graphic' \
	'graphic' \
	'false' \
	'Disables graphical output'

parameter \
	'qemu_logfile' \
	'one' \
	'logfile' \
	'logfile' \
	'' \
	'Duplicates all output to the log file'

parameter \
	'qemu_tempdir' \
	'one' \
	'tempdir' \
	'tempdir' \
	'$TMPDIR' \
	'Creates a temporary directory'

parameter \
	'qemu_watchdog' \
	'one' \
	'watchdog' \
	'' \
	'' \
	'Creates a virtual hardware watchdog device'

parameter \
	'qemu_disk' \
	'list' \
	'disk' \
	'' \
	'' \
	'Defines which disk image to use with this drive'

parameter \
	'qemu_device' \
	'list' \
	'device' \
	'' \
	'' \
	'Adds device driver and sets driver properties'

parameter \
	'qemu_virtfs' \
	'list' \
	'virtfs' \
	'' \
	'' \
	'Specifies the export path for the file system device'

parameter \
	'qemu_boot' \
	'one' \
	'boot' \
	'boot' \
	'' \
	'Specifies boot order drives as a string of drive letters'
fi
