#!/bin/sh -efu

if [ -z "${__include_vm_sh_functions-}" ]; then
__include_vm_sh_functions=1

vm_read_profile_config() {
	[ -n "$vm_profile" ] ||
		fatal "Profile name be specified"

	[ -s "$vm_config_file" ] ||
		fatal "Config file not found"

	git_config_location_exists "$vm_config_file" "vm.$vm_profile" ||
		fatal "Profile not exists: vm.$vm_profile"

	vm_read_config "$vm_config_file"
}

fi
