#!/bin/sh -efu

if [ -z "${__include_vm_sh_functions-}" ]; then
__include_vm_sh_functions=1

getopt_args=
generate_getopt_args() {
	local n c
	for n in $vm_params; do
		eval "c=\"\${${n}_cmdline-}\""
		[ -z "$c" ] ||
			getopt_args="$getopt_args$c:,"
	done
}

vm_params=' '
parameter() {
	local vartype varname cfgname cmdline default description

	varname="$1"; shift
	vartype="$1"; shift
	cfgname="$1"; shift
	cmdline="$1"; shift
	default="$1"; shift
	description="$1"; shift

	vm_params="$vm_params$varname "

	[ -z "$cmdline" ] ||
		eval "export ${varname}_cmdline=\"\$cmdline\""

	[ -z "$cfgname" ] ||
		eval "export ${varname}_cfgname=\"\$cfgname\""

	eval "export ${varname}_default=\"$default\""
	eval "export ${varname}_type=\"\$vartype\""
	eval "export ${varname}_description=\"\$description\""
}

fi
